export const featureDomains = [
  "about",
  "admin-packages",
  "admin-tokens",
  "auth",
  "channels",
  "chat",
  "contact",
  "dashboard",
  "errors",
  "health",
  "home",
  "invoices",
  "keys",
  "legal",
  "models",
  "performance-metrics",
  "playground",
  "pricing",
  "profile",
  "rankings",
  "redemption-codes",
  "setup",
  "subscription-plans",
  "subscriptions",
  "system-settings",
  "tickets",
  "usage-logs",
  "users",
  "vibecoding",
  "wallet",
] as const;

export type FeatureDomain = (typeof featureDomains)[number];
